changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - "dependabot[bot]"
      - "github-actions[bot]"

  categories:
    - title: Features
      labels:
        - enhancement
        - feature

    - title: Bug Fixes
      labels:
        - bug

    - title: Documentation
      labels:
        - documentation

    - title: Maintenance
      labels:
        - dependencies
        - chore

    - title: Other Changes
      labels:
        - "*"
